/* eslint-disable */
/*
 * MMA
 * The MMA API description
 *
 * The version of the OpenAPI document: 0.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoachEntity } from "./coachEntity";
import { LessonTypeEntity } from "./lessonTypeEntity";
import { ParticipantEntity } from "./participantEntity";

export class LessonDto {
  id: number;
  name: string;
  startDate: string;
  endDate: string;
  participants: Array<ParticipantEntity>;
  lessonType: LessonTypeEntity;
  coachOrder: Array<CoachEntity>;
}
